base: 'https://multisite-relation-site.ddev.site/independent/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: gb
    hreflang: ''
    websiteTitle: ''
  -
    title: German
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 2
sitePackage: site-independent-page
websiteTitle: ''
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435